= wsclient-cloudstore-poc
David Guzman <https://github.com/david-guzman[@david-guzman]>
:revnumber: {project-version}
:revdate: 10.01.2018
:revremark: First draft
:toc: macro
:toc-title: Contents

Java EE Timer-based JAX-RS client to cloud file store application to facilitate analysis of text content obtained from APIs (proof of concept).

*Source code:* https://github.com/UCL/wsclient-cloudstore-poc

.DRAFT
****
This document is only a rough draft.
These recommendations are subject to change.
****

toc::[]

== Background

=== Context

=== Objectives

=== Resources and platforms

==== Public APIs

==== PaaS - Heroku

==== UCL Office365 OneDrive

== Core components

=== wsclient-app

[plantuml, wsclient-sequence, svg]
....
box "wsclient-app"
control CallTimer <<Singleton EJB>>
control TimerService <<Container Resource>>
control TwitterCall <<Stateless EJB>>
control FileStore <<Stateless EJB>>
control MsGraphCall <<Stateless EJB>>
end box
collections PubAPIs as "Public APIs" <<HTTP Resource>>

CallTimer -> TimerService: @PostConstruct start timer
activate CallTimer
activate TimerService

TimerService --> TwitterCall: @Timeout fire event
activate TwitterCall
TimerService -> TimerService: next @Timeout
deactivate TimerService

TwitterCall ->] : <<Request>>
ref over PubAPIs: Twitter API
TwitterCall <-] : <<Response>>
TwitterCall -> FileStore : store JSON
activate FileStore

FileStore -> FileStore : create ZIP file
activate FileStore
FileStore -> MsGraphCall : upload
activate MsGraphCall
MsGraphCall ->] : <<Request>>
ref over PubAPIs: MS Graph API
MsGraphCall <-] : <<Response>>
deactivate MsGraphCall
deactivate FileStore
FileStore -> FileStore : delete ZIP file
deactivate FileStore
deactivate TwitterCall
....

=== wsclient-main

== Data flow

[plantuml, dataflow, svg]
....
cloud "Internet" {
    [Twitter API] -- GET
    GET --> [wsclient-cloudstore-app]
    [wsclient-cloudstore-app] --> PUT
    PUT -- [UCL Office365 OneDrive]
}

note right of [wsclient-cloudstore-app]
    Calls Twitter Search API
    Package and compress JSON in a ZIP file
    Push the ZIP file to OneDrive
end note

frame "CS UCL" {
    [UCL Office365 OneDrive] ..> API
    API -- [clientapp1]
    API -- [clientapp2]
    API -- [clientappn]
    
    [clientapp1] --> [data processor]
    [clientapp2] --> [data processor]
    [clientappn] --> [data processor]
    
    folder "storage" {
        [data processor] --> [objectstore]
        [data processor] --> [database]
        [data processor] --> [filestore]
        
    }
}

note right of API
    Python API
end note
....


== Future features
